[package]
name = "bulletproof"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
curve25519-dalek-ng = { version = "4.1", default-features = false, features = ["u64_backend"] }
merlin = "3.0"
bulletproofs = { version = "4.0", features = ["std"] }
